
export const SHOW_LOADER ='SHOW_LOADER';
export const HIDE_LOADER ='HIDE_LOADER';

export const FETCH_GAMES_START ='FETCH_GAMES_START';
export const FETCH_GAMES_SUCCESS ='FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAIL ='FETCH_GAMES_FAIL';




export const ADD_FAVOURITES_START ='ADD_FAVOURITES_START';
export const ADD_FAVOURITES_SUCCESS ='ADD_FAVOURITES_SUCCESS';
export const ADD_FAVOURITES_FAIL ='ADD_FAVOURITES_FAIL';

export const REMOVE_FAVOURITES_START ='REMOVE_FAVOURITES_START';
export const REMOVE_FAVOURITES_SUCCESS ='REMOVE_FAVOURITES_SUCCESS';
export const REMOVE_FAVOURITES_FAIL ='REMOVE_FAVOURITES_FAIL';