
export const SHOW_LOADER ='SHOW_LOADER';
export const HIDE_LOADER ='HIDE_LOADER';

export const FETCH_GAMES_START ='FETCH_GAMES_START';
export const FETCH_GAMES_SUCCESS ='FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAIL ='FETCH_GAMES_FAIL';

export const FETCH_EXACT_PATH_START=' FETCH_EXACT_PATH_START';
export const  FETCH_EXACT_PATH_SUCCESS ='FETCH_EXACT_PATH_SUCCESS';
export const  FETCH_EXACT_PATH_FAIL =' FETCH_EXACT_PATH_FAIL';

export const  FAVORITES_START='FAVORITES_START';
export const  FAVORITES_SUCCESS ='FAVORITES_SUCCESS';
export const  FAVORITES_FAIL ='FAVORITES_FAIL';

export const ADD_FAVOURITES_START ='ADD_FAVOURITES_START';
export const ADD_FAVOURITES_SUCCESS ='ADD_FAVOURITES_SUCCESS';
export const ADD_FAVOURITES_FAIL ='ADD_FAVOURITES_FAIL';

export const REMOVE_FAVOURITES_START ='REMOVE_FAVOURITES_START';
export const REMOVE_FAVOURITES_SUCCESS ='REMOVE_FAVOURITES_SUCCESS';
export const REMOVE_FAVOURITES_FAIL ='REMOVE_FAVOURITES_FAIL';