
export const SHOW_LOADER ='SHOW_LOADER';
export const HIDE_LOADER ='HIDE_LOADER';

export const FETCH_GAMES_START ='FETCH_GAMES_START';
export const FETCH_GAMES_SUCCESS ='FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAIL ='FETCH_GAMES_FAIL';





